### ISSUE TITLE
Creare entità e repository

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [RobertaConti-Jarvis/Ammazon-j#11]

**Comment by RobertaConti-Jarvis** [comment]
risoluzione parziale con Commit; 1fc957d359ec2b6eeeb6f7632b76dbc739733756
ATTENZIONE mancano le associazioni multiple

**Comment by RobertaConti-Jarvis** [comment]
risoluzione parziale con Commit; efbefa34b3538bb8b4d08ef0f0d13c55e0e26942
ATTENZIONE mancano le associazioni multiple

**Comment by RobertaConti-Jarvis** [comment]
risoluzione parziale  con commit: 53dc94db941de20890cedc15f568a3a206b46da8

**Comment by AulicinoDiego** [comment]
commit: 10b983aea4a804d0baac5bfaa633d3724ea30b7e

**Comment by AulicinoDiego** [comment]
commit: b5569696fd6822ff71d309880a8594350edcc903
