### ISSUE TITLE
Richiesta modifica appModule per nuovo componente paginazione

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [RobertaConti-Jarvis/Ammazon-j#17]

**Comment by Fmarro** [comment]
Approvato, pushate completata la modifica

**Comment by RobertaConti-Jarvis** [comment]
risoluzione parziale con commit: 8d58bf2aeeaaf7afa8d24e70915a0cf8f5c0e08c

**Comment by g-golia** [comment]
302f98d29d6834f94bc9504eaca4f872a404c6dd
