### ISSUE TITLE
Registrazione

### ISSUE THREAD

**Issue by AulicinoDiego** [RobertaConti-Jarvis/Ammazon-j#21]
implementare caso d'uso per la Registazione degli utenti

**Comment by AulicinoDiego** [comment]
commit: 6145bf2d269a1a83929f8eb4643a2a3738349b41

**Comment by AulicinoDiego** [comment]
commit: c5fbe4ed085d664456d9b1d7c110bb48499eeac1

**Comment by AulicinoDiego** [comment]
commit: 0430437323a23f2bf7114893325a10d88b339410

**Comment by RobertaConti-Jarvis** [comment]
Risoluzione parziale lato server. commit : d80fe3fb4f7b5eca6840b77ef1000c50fc496ead

**Comment by AulicinoDiego** [comment]
commit  : 98bdff7d299cd860407cbeb7219f07dd440249d8
commit :  45d228d61be974b957f1b4957db4dc6d6af47d4e

**Comment by AulicinoDiego** [comment]
commit: a36c941a786e60d1d42d8600f5cecf7dd6de854d

**Comment by AulicinoDiego** [comment]
commit: cb195689923dede0f15952f85b8712b3c80f0828
