### ISSUE TITLE
Log-in

### ISSUE THREAD

**Issue by AulicinoDiego** [RobertaConti-Jarvis/Ammazon-j#22]
implementare caso d'uso che permetta ad un utente registrato di accedere.

**Comment by AulicinoDiego** [comment]
commit: 6145bf2d269a1a83929f8eb4643a2a3738349b41

**Comment by AulicinoDiego** [comment]
commit: c5fbe4ed085d664456d9b1d7c110bb48499eeac1

**Comment by AulicinoDiego** [comment]
commit: 0430437323a23f2bf7114893325a10d88b339410

**Comment by RobertaConti-Jarvis** [comment]
risoluzione parziale lato server. commit: d80fe3fb4f7b5eca6840b77ef1000c50fc496ead

**Comment by AulicinoDiego** [comment]
commit: 06e9aeaac58af34419d9177586dda9d0d8627a1c

**Comment by AulicinoDiego** [comment]
commit: d109ddcc677a96c2dd21bd0e680ba208a24b337f
