### ISSUE TITLE
individuate incongruenze tra le entità degli utenti e l'interfaccia login e registrazione.

### ISSUE THREAD

**Issue by AulicinoDiego** [RobertaConti-Jarvis/Ammazon-j#24]
Nell'Entità Utente manca l'email  e nell'interfaccia registrazione non sono presenti i campi per l'insermento del nome, cognome e codice fiscale.

**Comment by RobertaConti-Jarvis** [comment]
modificato UML commit: fdd7dfd874d1a2bee8039d11bd027d476c13ce9e
