### ISSUE TITLE
UC Mostra carrello

### ISSUE THREAD

**Issue by luca-lezzerini** [RobertaConti-Jarvis/Ammazon-j#31]

**Comment by SamueleM21** [comment]
implementato lato client con commit: 0dff9bd82b999f271596b4b77b4df5a88a3b71ad

**Comment by lollo996** [comment]
implementato service e serviceImpl con commit c77c3013ac4102ac1e967ce9e9bdf2db3eb67b2c

**Comment by Matteosalvatori4** [comment]
chiuso con commit a689e7ff61f092ebf984299f5996913135c2acc2

**Comment by Matteosalvatori4** [comment]
chiuso con commit b5c031aeca78290089c31845c1fb74c61fa012ae
