### ISSUE TITLE
Gestione Account

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [RobertaConti-Jarvis/Ammazon-j#49]

**Comment by AulicinoDiego** [comment]
commit: f5acc25b207198efb68673cbbc30e08440ee7221

**Comment by AulicinoDiego** [comment]
commit: 2b08f9ccc83acec98bb10e7d7989f92e01ba2faa

**Comment by AulicinoDiego** [comment]
commit: d8804582154929d6153500508dc9f32ca152e391
