### ISSUE TITLE
Gestione Prodotti

### ISSUE THREAD

**Issue by luca-lezzerini** [RobertaConti-Jarvis/Ammazon-j#6]
CRUD

**Comment by RobertaConti-Jarvis** [comment]
Risoluzione parziale lato client con commit: f0ee6b8591f14b6f6e475bd80707a7a01716ccba

**Comment by RobertaConti-Jarvis** [comment]
Risoluzione parziale lato server con commit: 2f61fb6092a3a208afa47d884e8137f6fb7db3de

**Comment by AulicinoDiego** [comment]
commit: 302f98d29d6834f94bc9504eaca4f872a404c6dd
